
cuda:0
Traceback (most recent call last):
  File "c:\Users\Alvaro\Desktop\CNN_Project\src_gpu\runrunner.py", line 39, in <module>
    train_loader, valid_loader, num_classes = load_data(train_dir,
                                             ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Alvaro\Desktop\CNN_Project\src_gpu\cnn.py", line 235, in load_data
    train_data = torchvision.datasets.ImageFolder(train_dir, transform=train_transforms)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Alvaro\Desktop\CNN_Project\venv\Lib\site-packages\torchvision\datasets\folder.py", line 328, in __init__
    super().__init__(
  File "c:\Users\Alvaro\Desktop\CNN_Project\venv\Lib\site-packages\torchvision\datasets\folder.py", line 149, in __init__
    classes, class_to_idx = self.find_classes(self.root)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Alvaro\Desktop\CNN_Project\venv\Lib\site-packages\torchvision\datasets\folder.py", line 234, in find_classes
    return find_classes(directory)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Alvaro\Desktop\CNN_Project\venv\Lib\site-packages\torchvision\datasets\folder.py", line 41, in find_classes
    classes = sorted(entry.name for entry in os.scandir(directory) if entry.is_dir())
                                             ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada: '../dataset/training'